# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/gui/layouts/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 463)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 481, 441))
        self.tabWidget.setIconSize(QtCore.QSize(22, 22))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.cpu = QtWidgets.QWidget()
        self.cpu.setObjectName("cpu")
        self.tabWidget.addTab(self.cpu, "")
        self.gpu = QtWidgets.QWidget()
        self.gpu.setObjectName("gpu")
        self.tabWidget.addTab(self.gpu, "")
        self.storage = QtWidgets.QWidget()
        self.storage.setObjectName("storage")
        self.tabWidget.addTab(self.storage, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cpu), _translate("MainWindow", "CPU"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gpu), _translate("MainWindow", "GPU"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.storage), _translate("MainWindow", "Storage"))
